# Generated by Django 4.2.2 on 2023-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.SmallIntegerField(blank=True, default=2023, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imgs/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Online', 'Online'), ('Presencial', 'Presencial')], default='Online', max_length=20, null=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
