# Generated by Django 4.2.2 on 2023-07-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_remove_curso_tipo_alter_curso_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='valor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
