# Generated by Django 4.2.2 on 2023-07-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_curso_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='intrutor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
