# Generated by Django 4.2.2 on 2023-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_curso_intrutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(blank=True, choices=[('online', 'online'), ('presencial', 'presencial')], default='online', max_length=20, null=True),
        ),
    ]
