# Generated by Django 4.2.2 on 2023-07-14 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_curso_tipo'),
        ('cliente', '0002_venda_comprado_alter_venda_email_alter_venda_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administrador.curso'),
        ),
    ]
